version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: apple-music-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: apple_music_db
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
